apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hugo-site-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hugo-site
spec:
  hosts:
  - "*"
  gateways:
  - hugo-site-gateway
  http:
  - match:
    - uri:
        exact: /hugo-site
    route:
    - destination:
        host: hugo-site
        port:
          number: 8080
