name: Feature Branch Workflow

on:
  push:
    branches:
      - 'feature/*'

jobs:
  push-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Delete s3 content
        run: aws s3 rm s3://hugo-bucket-944aa7a --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
          AWS_DEFAULT_OUTPUT: json

      - name: Generate static files
        run: hugo
